version: '2'
services:
  martenblog:
    image: martenblog
    container_name: martenblog
    depends_on:
      - redis
    volumes:
      - ./thurk:/opt/app
    ports:
      - "3033:3033"
    depends_on:
      - nginx-proxy
      - minkmongo
    environment:
      - VIRTUAL_HOST=blog.thinklikeamink.net,blog.thinklikeamink.org
  minkmongo:
    image: minkmongo
    container_name: minkmongo
    volumes:
      - /var/lib/mongodb:/data/db
    ports:
      - "27017:27017"
  nginx-proxy:
    image: nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DEFAULT_HOST=thinklikeamink.net,thinklikeamink.org
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/sites-available:/opt/nginx-proxy/sites-static
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /etc/nginx/certs:/etc/nginx/certs
